name: Release

on:
  push:
    branches:
      - master

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Basic permissions for npm publishing
permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Make sure we get all tags
          fetch-tags: true
          # Use PAT instead of GITHUB_TOKEN
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Fast-forward branch
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name  "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.RELEASE_TOKEN }}@github.com/dittonetwork/sdk-js.git
          git fetch origin master --tags
          git checkout -B master origin/master
          git rev-list --left-right --graph --oneline HEAD...origin/master || true

      - name: Setup pnpm 8
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: pnpm i

      - name: TypeScript Type Check
        run: pnpm tsc --noEmit --project ./packages/core/tsconfig.json

      - name: Lint
        run: pnpm lint

      - name: Run Tests
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Setup npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > ~/.npmrc
          npm config set access public

      - name: Semantic Release Core Package
        run: |
          echo "::group::REMOTE LOG BEFORE"
          git log -3 --oneline origin/master
          git fetch origin master --quiet
          echo "::endgroup::"
          git fetch origin master --tags          # подтянуть свежее
          git rev-list --left-right --count master...origin/master  # должно вывести 0 0
          git checkout -B master origin/master    # атомарно перезаписать локальную ветку
          npx semantic-release -e semantic-release-monorepo
          echo "::group::REMOTE LOG AFTER"
          git log -3 --oneline origin/master
          git fetch origin master --quiet
          echo "::endgroup::"
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          DEBUG: semantic-release:branches
